# Generated by Django 5.2.6 on 2025-09-29 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(help_text='Unique internal identifier (e.g., NBC_001)', max_length=100, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only digit characters are allowed.')])),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only digit characters are allowed.')])),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('target_default', models.BooleanField(default=False, help_text='False=Repaid/Non-Default, True=Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
