# Generated by Django 5.2.6 on 2025-09-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_timestamp', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(max_length=50)),
                ('merchant_category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('billing_cycle_start', models.DateField()),
                ('billing_cycle_end', models.DateField()),
                ('kwh_consumption', models.IntegerField()),
                ('meter_reading_new', models.IntegerField()),
                ('due_date', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=100, unique=True)),
                ('loan_scheme', models.CharField(max_length=255)),
                ('sanction_date', models.DateField()),
                ('original_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_tenure_months', models.IntegerField()),
                ('business_activity_code', models.IntegerField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='EmiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_record_id', models.CharField(max_length=100, unique=True)),
                ('emi_due_date', models.DateField()),
                ('emi_paid_date', models.DateField(blank=True, null=True)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status_detailed', models.CharField(max_length=50)),
                ('dpd_days', models.IntegerField(default=0, help_text='Days Past Due')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='api.loan')),
            ],
        ),
        migrations.CreateModel(
            name='MobileRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=50)),
                ('bill_payment_date', models.DateField()),
                ('recharge_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validity_days', models.IntegerField()),
                ('payment_source', models.CharField(max_length=50)),
                ('is_auto_pay', models.BooleanField(default=False)),
                ('data_usage_gb', models.FloatField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration_card_id', models.CharField(max_length=100, unique=True)),
                ('card_type', models.CharField(max_length=50)),
                ('num_family_members', models.IntegerField()),
                ('member_aadhar_list', models.TextField(blank=True, help_text='Comma-separated list of Aadhar numbers', null=True)),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ration_card', to='api.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='PDSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('item_name', models.CharField(max_length=100)),
                ('allocated_quantity_kg', models.FloatField()),
                ('actual_uptake_quantity_kg', models.FloatField()),
                ('uptake_ratio', models.FloatField()),
                ('ration_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pds_transactions', to='api.rationcard')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=100, unique=True)),
                ('utility_type', models.CharField(choices=[('Water', 'Water'), ('Gas', 'Gas'), ('Property Tax', 'Property Tax'), ('Sewerage', 'Sewerage')], max_length=20)),
                ('billing_period', models.CharField(max_length=50)),
                ('bill_due_date', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metered_consumption', models.FloatField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='api.beneficiary')),
            ],
        ),
    ]
